package database

import (
	"time"

	"github.com/google/uuid"

	"idea-collision-engine-api/internal/models"
)

// GetCollisionDomainSeeds returns curated collision domains for seeding
func GetCollisionDomainSeeds() []models.CollisionDomain {
	now := time.Now()
	return []models.CollisionDomain{
		// Basic tier domains (from frontend)
		{
			ID:          uuid.New().String(),
			Name:        "Biomimicry",
			Category:    "Nature & Biology",
			Description: "How nature solves similar problems through millions of years of evolution",
			Examples:    []string{"Velcro from burdock burrs", "Bullet train design from kingfisher beaks", "Self-healing materials from plant tissues"},
			Keywords:    []string{"evolution", "adaptation", "efficiency", "sustainability", "natural selection"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Ancient Civilizations",
			Category:    "Historical",
			Description: "Time-tested approaches and wisdom from past cultures",
			Examples:    []string{"Roman concrete lasting 2000 years", "Incan agricultural terraces", "Greek philosophical methods"},
			Keywords:    []string{"wisdom", "durability", "systems", "culture", "timeless"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Game Design",
			Category:    "Entertainment",
			Description: "Engagement mechanics, progression systems, and motivation psychology",
			Examples:    []string{"Leveling systems for skill building", "Achievement badges for motivation", "Balancing challenge and reward"},
			Keywords:    []string{"engagement", "progression", "feedback", "motivation", "flow state"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Music Theory",
			Category:    "Arts",
			Description: "Harmony, dissonance, rhythm, and emotional resonance principles",
			Examples:    []string{"Tension and resolution in storytelling", "Rhythmic patterns in UI design", "Harmonic collaboration"},
			Keywords:    []string{"harmony", "rhythm", "resonance", "emotion", "pattern"},
			Intensity:   []string{"gentle", "moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Quantum Physics",
			Category:    "Science",
			Description: "Counterintuitive principles of reality at the smallest scales",
			Examples:    []string{"Quantum entanglement for instant connections", "Superposition for multiple states", "Observer effect on outcomes"},
			Keywords:    []string{"uncertainty", "entanglement", "superposition", "probability", "observation"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Culinary Arts",
			Category:    "Crafts",
			Description: "Flavor combinations, timing, temperature, and transformation processes",
			Examples:    []string{"Mise en place for project preparation", "Flavor pairing for idea combinations", "Fermentation for gradual development"},
			Keywords:    []string{"transformation", "combination", "timing", "balance", "craft"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Ecosystem Dynamics",
			Category:    "Nature",
			Description: "Complex interdependencies, feedback loops, and emergent behaviors",
			Examples:    []string{"Symbiotic partnerships", "Succession patterns", "Keystone species effects"},
			Keywords:    []string{"interdependence", "cycles", "balance", "emergence", "resilience"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Theater & Performance",
			Category:    "Arts",
			Description: "Character development, dramatic structure, and audience engagement",
			Examples:    []string{"Three-act structure for project phases", "Method acting for user empathy", "Improvisation for adaptability"},
			Keywords:    []string{"character", "narrative", "audience", "transformation", "presence"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Martial Arts",
			Category:    "Philosophy",
			Description: "Balance, timing, energy redirection, and mental discipline",
			Examples:    []string{"Using opponent's force in negotiations", "Flow state in difficult tasks", "Defensive positioning"},
			Keywords:    []string{"balance", "timing", "discipline", "flow", "strategy"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Astronomy",
			Category:    "Science",
			Description: "Scale, cycles, gravitational relationships, and cosmic perspectives",
			Examples:    []string{"Orbital mechanics for sustainable cycles", "Gravitational wells for user retention", "Star formation for growth"},
			Keywords:    []string{"scale", "cycles", "gravity", "perspective", "formation"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Cultural Anthropology",
			Category:    "Human Systems",
			Description: "Cultural patterns, rituals, social structures, and human universals",
			Examples:    []string{"Ritual design for user onboarding", "Gift economies for community building", "Rite of passage for skill mastery"},
			Keywords:    []string{"culture", "ritual", "community", "meaning", "tradition"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Architecture",
			Category:    "Design",
			Description: "Space, flow, structure, and human experience of built environments",
			Examples:    []string{"Flow patterns for user journeys", "Load-bearing structures for system design", "Natural light for attention"},
			Keywords:    []string{"space", "flow", "structure", "experience", "foundation"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Neuroscience",
			Category:    "Science",
			Description: "Brain networks, learning mechanisms, and cognitive biases",
			Examples:    []string{"Neural pathways for habit formation", "Plasticity for adaptive systems", "Mirror neurons for empathy"},
			Keywords:    []string{"networks", "plasticity", "learning", "patterns", "connection"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "World Mythology",
			Category:    "Cultural",
			Description: "Universal stories, archetypal patterns, and symbolic meaning",
			Examples:    []string{"Hero's journey for user transformation", "Creation myths for origin stories", "Trickster figures for innovation"},
			Keywords:    []string{"archetype", "journey", "transformation", "symbol", "universal"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Economic Systems",
			Category:    "Social Systems",
			Description: "Incentives, markets, scarcity, and value creation mechanisms",
			Examples:    []string{"Network effects for growth", "Scarcity for desire", "Liquidity for accessibility"},
			Keywords:    []string{"incentives", "value", "exchange", "scarcity", "networks"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		
		// Additional domains to reach 50+
		{
			ID:          uuid.New().String(),
			Name:        "Urban Planning",
			Category:    "Design",
			Description: "City flow, zoning, infrastructure, and human-scale environments",
			Examples:    []string{"Traffic flow for data routing", "Mixed-use zoning for feature integration", "Public spaces for community features"},
			Keywords:    []string{"flow", "infrastructure", "scale", "planning", "accessibility"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Sailing & Navigation",
			Category:    "Sports",
			Description: "Wind patterns, course correction, and adaptive navigation",
			Examples:    []string{"Tacking against headwinds", "Reading environmental signals", "Course correction techniques"},
			Keywords:    []string{"adaptation", "navigation", "wind", "course", "signals"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Beekeeping",
			Category:    "Nature",
			Description: "Colony organization, communication systems, and collective intelligence",
			Examples:    []string{"Waggle dance communication", "Swarm decision-making", "Seasonal adaptation"},
			Keywords:    []string{"collective", "communication", "organization", "adaptation", "swarm"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Emergency Medicine",
			Category:    "Medical",
			Description: "Triage, rapid decision-making, and resource allocation under pressure",
			Examples:    []string{"Triage protocols for feature prioritization", "Rapid diagnosis techniques", "Resource allocation under constraints"},
			Keywords:    []string{"triage", "urgency", "diagnosis", "pressure", "allocation"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Documentary Filmmaking",
			Category:    "Media",
			Description: "Truth-telling, narrative construction, and audience engagement",
			Examples:    []string{"Story arc construction", "Truth verification methods", "Audience engagement techniques"},
			Keywords:    []string{"narrative", "truth", "engagement", "story", "construction"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Origami",
			Category:    "Arts",
			Description: "Transformation through folding, constraint-based creation, and emergent complexity",
			Examples:    []string{"Complex forms from simple folds", "Constraint-driven design", "Incremental complexity"},
			Keywords:    []string{"transformation", "constraints", "folding", "complexity", "emergence"},
			Intensity:   []string{"gentle", "moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Wilderness Survival",
			Category:    "Skills",
			Description: "Resource optimization, adaptation, and resilience under extreme constraints",
			Examples:    []string{"Multi-purpose tool usage", "Resource conservation", "Environmental adaptation"},
			Keywords:    []string{"survival", "adaptation", "resources", "resilience", "constraints"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Jazz Improvisation",
			Category:    "Music",
			Description: "Spontaneous creation, call-and-response, and structured freedom",
			Examples:    []string{"Real-time collaboration", "Structured improvisation", "Call-and-response patterns"},
			Keywords:    []string{"improvisation", "spontaneity", "collaboration", "structure", "freedom"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Permaculture",
			Category:    "Agriculture",
			Description: "Sustainable design, ecological principles, and regenerative systems",
			Examples:    []string{"Closed-loop systems", "Companion planting strategies", "Regenerative practices"},
			Keywords:    []string{"sustainability", "ecology", "regenerative", "loops", "design"},
			Intensity:   []string{"gentle", "moderate"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Stand-up Comedy",
			Category:    "Performance",
			Description: "Timing, audience reading, and finding humor in unexpected places",
			Examples:    []string{"Comedic timing techniques", "Audience feedback loops", "Unexpected perspective shifts"},
			Keywords:    []string{"timing", "humor", "unexpected", "audience", "perspective"},
			Intensity:   []string{"gentle", "moderate", "radical"},
			Tier:        "basic",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		
		// Premium tier domains (more advanced/specialized)
		{
			ID:          quantum_uuid(),
			Name:        "Chaos Theory",
			Category:    "Mathematics",
			Description: "Sensitive dependence, strange attractors, and emergent order from randomness",
			Examples:    []string{"Butterfly effect in system design", "Strange attractors in user behavior", "Order from chaos principles"},
			Keywords:    []string{"chaos", "emergence", "sensitivity", "attractors", "nonlinear"},
			Intensity:   []string{"radical"},
			Tier:        "premium",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Mycorrhizal Networks",
			Category:    "Biology",
			Description: "Underground fungal networks that connect and support forest ecosystems",
			Examples:    []string{"Distributed resource sharing", "Network resilience patterns", "Symbiotic relationships"},
			Keywords:    []string{"networks", "symbiosis", "distribution", "support", "underground"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "premium",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Cryptography",
			Category:    "Security",
			Description: "Information hiding, key management, and secure communication protocols",
			Examples:    []string{"Zero-knowledge proofs", "Perfect forward secrecy", "Distributed trust systems"},
			Keywords:    []string{"security", "trust", "protocols", "verification", "distribution"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "premium",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Particle Physics",
			Category:    "Science",
			Description: "Fundamental interactions, field theories, and emergent properties from basic components",
			Examples:    []string{"Emergent properties from simple rules", "Field interaction patterns", "Conservation laws"},
			Keywords:    []string{"fundamental", "interactions", "emergence", "fields", "conservation"},
			Intensity:   []string{"radical"},
			Tier:        "premium",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          uuid.New().String(),
			Name:        "Memetics",
			Category:    "Psychology",
			Description: "Information transmission, viral spread, and cultural evolution patterns",
			Examples:    []string{"Viral content mechanisms", "Cultural transmission patterns", "Memetic evolution"},
			Keywords:    []string{"transmission", "viral", "evolution", "culture", "spread"},
			Intensity:   []string{"moderate", "radical"},
			Tier:        "premium",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
	}
}

// Helper function to generate predictable UUIDs for consistent seeding
func quantum_uuid() string {
	// This creates a deterministic UUID for quantum domain
	return "550e8400-e29b-41d4-a716-446655440000"
}